# -*- coding: utf-8 -*-
"""ColoranoGAN_Train.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6xnLiw45uNecv0yhs7MZj-0sH8bmqBz
"""

gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

from google.colab import drive
drive.mount('/content/drive')

!pip install -r requirements.txt
!pip install fastai --upgrade
!python train.py --resume --save_filename /content/drive/MyDrive/02456/models/epoch22.pt